/* eslint-disable */
export default {
  "key": "checkout",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Checkout",
        "adjustPin": "Adjust pin",
        "back": "Back",
        "delivery": "Delivery",
        "pickup": "Pickup",
        "where": "Where?",
        "selectedAddress": "Selected Address",
        "chooseAddress": "Choose address",
        "tapToChoose": "Tap to choose or find location",
        "leaveAtDoor": "Leave order at the door",
        "sendAsGift": "Send as a gift",
        "active": "Active",
        "addCourierNote": "Add note for the courier",
        "when": "When?",
        "priority": "Priority",
        "priorityDesc": "25-35 min • Direct to you",
        "new": "New",
        "standard": "Standard",
        "standardDesc": "30-40 min",
        "schedule": "Schedule",
        "scheduleDesc": "Choose a delivery time",
        "orderItems": "Order items",
        "addMore": "Add more",
        "addVenueComment": "Add comment for venue",
        "venueCommentPlaceholder": "Special requests, allergies, or any context for the chef...",
        "edit": "Edit",
        "add": "Add",
        "payment": "Payment",
        "paymentMethod": "Payment method",
        "card": "Visa/Mastercard",
        "cash": "Pay by Cash",
        "credits": "Wolt Credits",
        "tapToChangePayment": "Tap to change payment method",
        "promoPlaceholder": "Enter gift card or promo code",
        "submit": "Submit",
        "addCourierTip": "Add courier tip",
        "tipDesc": "They'll get 100% of your tip after the delivery.",
        "other": "Other",
        "summary": "Summary",
        "inclTaxes": "Incl. taxes (if applicable)",
        "howFeesWork": "How fees work",
        "subtotal": "Item subtotal",
        "bagFee": "Bag fee",
        "serviceFee": "Service fee",
        "deliveryFee": "Delivery",
        "total": "Total",
        "onlyWithWoltPlus": "Only with Wolt+",
        "woltPlusPromo": "Get AZN 0 delivery fee and more with Wolt+.",
        "learnMore": "Learn more",
        "startSaving": "Start saving now",
        "pleaseAddPayment": "Please add a payment method to",
        "continueWithOrder": "continue with your order",
        "finishOrder": "Finish order",
        "selectAddressError": "Please select or add a delivery address.",
        "noteForCourier": "Note for the courier",
        "notePlaceholder": "Door code, building number, or how to reach you...",
        "cancel": "Cancel",
        "saveNote": "Save note",
        "saveComment": "Save"
      },
      "tr": {
        "title": "Ödeme",
        "adjustPin": "Pimi ayarla",
        "back": "Geri",
        "delivery": "Teslimat",
        "pickup": "Gel-al",
        "where": "Nereye?",
        "selectedAddress": "Seçili Adres",
        "chooseAddress": "Adres seçin",
        "tapToChoose": "Konumu seçmek veya bulmak için dokunun",
        "leaveAtDoor": "Siparişi kapıya bırak",
        "sendAsGift": "Hediye olarak gönder",
        "active": "Aktif",
        "addCourierNote": "Kurye için not ekle",
        "when": "Ne zaman?",
        "priority": "Öncelikli",
        "priorityDesc": "25-35 dk • Doğrudan size",
        "new": "Yeni",
        "standard": "Standart",
        "standardDesc": "30-40 dk",
        "schedule": "Planla",
        "scheduleDesc": "Bir teslimat zamanı seçin",
        "orderItems": "Sipariş ürünleri",
        "addMore": "Daha fazla ekle",
        "addVenueComment": "Mekan için yorum ekle",
        "venueCommentPlaceholder": "Özel istekler, alerjiler veya şef için herhangi bir not...",
        "edit": "Düzenle",
        "add": "Ekle",
        "payment": "Ödeme",
        "paymentMethod": "Ödeme yöntemi",
        "card": "Visa/Mastercard",
        "cash": "Nakit Öde",
        "credits": "Wolt Kredileri",
        "tapToChangePayment": "Ödeme yöntemini değiştirmek için dokunun",
        "promoPlaceholder": "Hediye kartı veya promosyon kodu girin",
        "submit": "Gönder",
        "addCourierTip": "Kurye bahşişi ekle",
        "tipDesc": "Teslimattan sonra bahşişinizin %100'ü onlara ulaşacaktır.",
        "other": "Diğer",
        "summary": "Özet",
        "inclTaxes": "Vergiler dahil (varsa)",
        "howFeesWork": "Ücretler nasıl işler?",
        "subtotal": "Ürün ara toplamı",
        "bagFee": "Poşet ücreti",
        "serviceFee": "Hizmet ücreti",
        "deliveryFee": "Teslimat",
        "total": "Toplam",
        "onlyWithWoltPlus": "Sadece Wolt+ ile",
        "woltPlusPromo": "Wolt+ ile 0 AZN teslimat ücreti ve daha fazlasını alın.",
        "learnMore": "Daha fazla bilgi al",
        "startSaving": "Şimdi tasarruf etmeye başlayın",
        "pleaseAddPayment": "Siparişinize devam etmek için",
        "continueWithOrder": "lütfen bir ödeme yöntemi ekleyin",
        "finishOrder": "Siparişi tamamla",
        "selectAddressError": "Lütfen bir teslimat adresi seçin veya ekleyin.",
        "noteForCourier": "Kurye için not",
        "notePlaceholder": "Kapı kodu, bina numarası veya size nasıl ulaşılacağı...",
        "cancel": "İptal",
        "saveNote": "Notu kaydet",
        "saveComment": "Kaydet"
      }
    }
  },
  "localIds": [
    "checkout::local::components\\View\\main\\checkoutView\\checkout.content.ts"
  ]
} as const;
