import React from "react";
import type { Metadata } from "next";
import { Fredoka, Poppins } from "next/font/google";
import "../globals.css";
import MainLayout from "@/components/layout/MainLayout";

const fontFredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});
const fontPoppins = Poppins({
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontFredoka.variable} ${fontPoppins.variable} antialiased`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
